### ISSUE TITLE
Bug: Interpreters become one-time-use when called from js

### ISSUE THREAD

**Issue by MichaelXavier** [purescript/purescript-free#22]
This is a strange one, so I've set up a repo that reproduces the issue:

https://github.com/MichaelXavier/purescript-free-bug

I've got a stripped down version of the example that uses the coyoneda free and goEffC. The issue is that if you call effectful code that runs the interpreter multiple times from JS, it only gets run once. I suspect this may be a bug in `goEffC`. I don't know if this extends to the other free patterns. I've noted in the readme that if you construct a new interpreter at every use (e.g. `i <- return myInterpreter`), the code behaves as expected.

**Comment by garyb** [comment]
I'm pretty sure this is no longer a problem too, we haven't had `goEff` for a while.
