### ISSUE TITLE
Error in running the examples.

### ISSUE THREAD

**Issue by wpoosanguansit** [purescript/purescript-free#24]
HI,

I get an error:

Error in declaration main
No instance found for Prelude.Show (Control.Monad.Eff.Eff (trace :: Debug.Trace.Trace) Prelude.Unit)

when i try to run the examples in the psci.  Is there some setup I need to make to get it running in the interactive mode?  Things compile and load fine and fail when the main is called.  Thanks for your help.

**Comment by paf31** [comment]
`psci` doesn't support the `Eff` monad since it doesn't have a `Show` instance. `psci` only supports evaluation of pure expressions right now.

**Comment by wpoosanguansit** [comment]
Thank you, Phil.  I hope you don't mind I ask how I can run the code in this case?  I am trying to learn how to encode programs using Free Monad and Coyoneda from the example you have.  It will be really helpful if I can run the code.  Thank you for your great work.

**Comment by garyb** [comment]
In this project the examples are set up to compile (and run) as part of the Grunt task.

If you just want to build the examples you can run:

```
grunt psc
```

And then you can just run them as normal with `node`:

```
node tmp/Teletype.js
node tmp/TeletypeCoproduct.js
```

**Comment by wpoosanguansit** [comment]
Thank you Gary.  Will try that out.

**Comment by ethul** [comment]
As a note, you can also do 'grunt example' to comple and run the examples.

**Comment by garyb** [comment]
Closing this now as things have changed a bit now and the examples should be runnable in psci.
