### ISSUE TITLE
Why do we have both pure and pureF?

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-free#30]
If there are some situations where one is better suited to the other and vice versa, could this be added to the documentation?

**Comment by garyb** [comment]
I think there definitely is, but I don't know a concrete example - it probably depends on what `f` is, and what you're doing with the result.

The difference is the data structure you get back - if you use `pure` the functor is not used in the returned `Free` structure at all (`Pure x`), whereas it is when you use `pureF` you get `Free (f (Pure x))`.

Perhaps @paf31, @jdegoes, @ethul, or anyone out there has a better understanding and can illustrate a case that we can use to document? :smile:

**Comment by garyb** [comment]
I assume the reason we have both is so we don't have to impose `Applicative f` on the `Free f` instance for `Applicative` (it only requires `Functor`, but `pureF` does require the `Applicative`), but that doesn't really answer the question of when you'd need `pureF`.

**Comment by jdegoes** [comment]
> but that doesn't really answer the question of when you'd need pureF.

I'm not sure why it's useful. After all, the whole point of a free monad is that you get a monad for free out of any functor. If it has `Applicative`, OK, then you can use its `pure` function, but why when `Free` gives you pure for "free"?

Possibly worth deleting it in the next version bump.

**Comment by ethul** [comment]
Is this okay to close? There is no more pureF in master

**Comment by garyb** [comment]
Yep :+1:

**Comment by ethul** [comment]
Thanks!
