### ISSUE TITLE
Free Applicative

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript/purescript-free#44]
I'd like to implement the Free Applicative.  Do we want it in this library, or should I start a new one?

**Comment by garyb** [comment]
Which one? I think there are at least 4 varieties of it :smile:

I'd suggest perhaps starting a new library for it, despite the name of this library it's mainly the free and cofree monad it's concerned with; the free semiring lives in `purescript-semirings`, for example.

**Comment by jdegoes** [comment]
Great idea. Maybe `purescript-freeap`?

**Comment by paf31** [comment]
https://github.com/ethul/purescript-freeap

**Comment by LiamGoodacre** [comment]
Ah awesome, it already exists :smile: - it's not on Pursuit which was where I was looking.

**Comment by jdegoes** [comment]
Might be a good idea to pull into contrib, /cc @ethul.

**Comment by ethul** [comment]
@jdegoes I am happy to move it to contrib or somewhere else. Just let me know.

**Comment by rightfold** [comment]
Any new thoughts on this? I think it would be nice to merge it into this package.

**Comment by garyb** [comment]
It lives here https://github.com/ethul/purescript-freeap
