### ISSUE TITLE
Rearrange `unfoldCofree` arguments?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-free#64]
Currently we have:

``` purescript
unfoldCofree
  :: forall f s a
   . Functor f
  => s
  -> (s -> a)
  -> (s -> f s)
  -> Cofree f a
```

I think perhaps this would seem more natural, given the kind of argument order we usually use:
``` purescript
unfoldCofree
  :: forall f s a
   . Functor f
  => (s -> a)
  -> (s -> f s)
  -> s
  -> Cofree f a
```

**Comment by paf31** [comment]
Seems fine, but maybe we should include this with the next breaking change?

**Comment by garyb** [comment]
Yeah definitely, it's not at all important - just wanted to open this for the next time we do do that. :)
