### ISSUE TITLE
`Eq` and `Ord` are unusable for `Free` and `Cofree`

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-free#71]
I probably should have tested #67 a bit more... I think we have to use `Eq1` / `Ord1` after all for it to be possible in PS.

@paf31 If we were going to put those somewhere in core, any thoughts where? `purescript-functors` perhaps? A bit weird, but...

**Comment by paf31** [comment]
In what sense are they unusable?

**Comment by garyb** [comment]
```
  Type class instance for

    Data.Eq.Eq (Cofree List a0)

  is possibly infinite.

while solving type class constraint

  Data.Eq.Eq (List (Cofree List a0))
```

**Comment by paf31** [comment]
Ah ok. I'm not sure where I'd prefer they go. What about in `Prelude` itself? Or we could create a `lifted-classes` library. Of course, when we get constraint kinds, we can do this once with `Data.Lifted`.

**Comment by garyb** [comment]
Adding them to `Prelude` is fine by me!
