### ISSUE TITLE
Add coiter

### ISSUE THREAD

**Issue by coot** [purescript/purescript-free#76]
[Like here](https://github.com/coot/purescript-dsl-example/blob/master/src/DSL/Utils.purs#L27). It is in [Haskell's Cofree module](https://hackage.haskell.org/package/free-4.12.4/docs/Control-Comonad-Cofree.html)

**Comment by paf31** [comment]
I think this is just `flip unfoldCofree id`?

**Comment by coot** [comment]
Indeed.

**Comment by paf31** [comment]
I'm not saying we shouldn't add it 😄
