### ISSUE TITLE
Free monad could be an instance of MMonad

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-free#84]
I think Free monad could be an instance of [`MFunctor and MMonad` ](https://github.com/Thimoteus/purescript-mmorph/blob/master/docs/Control/Monad/Morph.md#mmonad)

```purescript 
hoist = hoistFree
embed = foldFree
```

**Comment by natefaubion** [comment]
`Free` is not a `MonadTrans`.

**Comment by garyb** [comment]
We avoid non-core dependencies for the core libraries too, so if it was a valid instance it'd want defining in mmorph instead of here.

`FreeT` could be `MFunctor` and `MMonad` though!

**Comment by paf31** [comment]
Please open an issue on the `mmorph` repo.
