### ISSUE TITLE
Expose `Cofree` constructor

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-free#90]
Currently there's no way to make a single lazy Cofree node since the constructor is not exported, and mkCofree is strict.

**Comment by paulyoung** [comment]
Does `defer` not make it lazy?

**Comment by natefaubion** [comment]
`mkCofree` uses defer, but it takes the argument strictly https://github.com/purescript/purescript-free/blob/master/src/Control/Comonad/Cofree.purs#L40. If you added your own defer you'd have Lazy leaves, but not a Lazy spine.

**Comment by paf31** [comment]
Exporting it is fine with me 👍

**Comment by hdgarrood** [comment]
Was this resolved by #92?

**Comment by natefaubion** [comment]
Yes, you can use `deferCofree` now.
